Repository Van-sh/Grocery-Planner, pull requests merged in 2024-09, with the labels that each got.

#16 6: Add delete modal on delete click and other bugs/warning fixes
  src/assets/plus.jsx
  src/planner/ingredients/createForm/index.tsx
  src/planner/ingredients/index.tsx
  src/planner/ingredients/table.tsx
Labels: bug, feature, hygiene

#22 20: Add pagination in getAllIngredients
  src/planner/ingredients/api.ts
  src/planner/ingredients/index.tsx
  src/planner/ingredients/types.ts
Labels: feature

#19 10 fix audit issues
  package-lock.json
Labels: hygiene

#24 23 search ingredients
  src/common/autoComplete/index.tsx
  src/common/search.tsx
  src/constants.ts
  src/planner/ingredients/api.ts
  src/planner/ingredients/cards.tsx
  src/planner/ingredients/index.tsx
  src/planner/ingredients/types.ts
Labels: feature
